version: '3.8'

services:
  php-apache:
    build: .
    container_name: bgbj-php
    volumes:
      - ./html_dev:/var/www/html
    ports:
      - "8080:80"
    networks:
      - shared-net
    restart: always

networks:
  shared-net:
    external:
      name: shared-net
